package FitnessLife;


import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Alumnos;
import logica.Rutinas;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;



public class FitnessApp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FitnessApp.class.getName());

    
    DefaultTableModel tablaAlumno = new DefaultTableModel();
    DefaultTableModel modelo2 = new DefaultTableModel();
    JTable jTableAlumnos = new JTable(tablaAlumno);
    ArrayList<Alumnos> listaAlumnos = new ArrayList<Alumnos>();
    ArrayList<Rutinas> listaRutinas = new ArrayList<Rutinas>();
    
  
    
    public void refrescarTablaAlumno(){
        while(tablaAlumno.getRowCount()>0){
            tablaAlumno.removeRow(0);
        }
    
        
        for (Alumnos alumno : listaAlumnos){
        Object a[] = new Object[8];
        a[0] = alumno.getNombre();
        a[1] = alumno.getApellido();
        a[2] = alumno.getDni();
        a[3] = alumno.getPeso();
        a[4] = alumno.getAltura();
        a[5] = alumno.getGenero();
        a[6] = alumno.getRutina();
        a[7] = alumno.getDias();
        tablaAlumno.addRow(a);
        }
        tblRegistroAlumnos.setModel(tablaAlumno);
    }
    
    public void refrescarTablaRutina(){
        while(modelo2.getRowCount()>0){
            modelo2.removeRow(0);
        }
        for (Rutinas rutina : listaRutinas){
        Object r[] = new Object[6];
        r[0] = rutina.getEjercicio();
        r[1] = rutina.getSeriesRepeticiones();
        r[2] = rutina.getPesoEjercicio();
        r[3] = rutina.getDescanso();
        r[4] = rutina.getMusculoObjetivo();
        r[5] = rutina.getDia();
        modelo2.addRow(r);
        }
        tblRutinas.setModel(modelo2);
    }
    
    public FitnessApp() {
    initComponents();
    InitStyles();
    this.setTitle("Alumnos");
    this.setSize(900, 700);
    this.setLocationRelativeTo(null);
    
    jTableAlumnos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    jTableAlumnos.setRowSelectionAllowed(true);
    jTableAlumnos.setColumnSelectionAllowed(false);
    
    // Configurar tabla de alumnos
    tablaAlumno.addColumn("Nombre");
    tablaAlumno.addColumn("Apellido");
    tablaAlumno.addColumn("DNI");
    tablaAlumno.addColumn("Peso(KG)");
    tablaAlumno.addColumn("Altura");
    tablaAlumno.addColumn("Género");
    tablaAlumno.addColumn("Rutina");
    tablaAlumno.addColumn("Dias/semana");
    refrescarTablaAlumno();
    
    // AGREGAR: Configurar tabla de rutinas
    modelo2.addColumn("Ejercicios");
    modelo2.addColumn("Series/Repeticiones");
    modelo2.addColumn("PesoEjercicio");
    modelo2.addColumn("Descanso");
    modelo2.addColumn("Musculo Objetivo");
    modelo2.addColumn("Dia");
    refrescarTablaRutina();
}
    private void InitStyles(){
        
        txtMensaje.putClientProperty( "FlatLaf.style", "font: 14 $light.font" );
        txtMensaje.setForeground(Color.black);
    }
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        SuperiorLila = new javax.swing.JPanel();
        txtBuenosDias = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        PilarVioleta = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblFitnessLife = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelAlumnos = new javax.swing.JPanel();
        BotonAñadir = new javax.swing.JButton();
        btnBorrarAlumno = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegistroAlumnos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        txtApellidoAlumno = new javax.swing.JTextField();
        txtDniAlumno = new javax.swing.JTextField();
        txtPesoAlumno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDiasAlumno = new javax.swing.JTextField();
        txtAlturaAlumno = new javax.swing.JTextField();
        cboGeneroAlumno = new javax.swing.JComboBox<>();
        cboRutina = new javax.swing.JComboBox<>();
        PanelRutinas = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEjerciciosRutina = new javax.swing.JTextField();
        txtSeriesRutina = new javax.swing.JTextField();
        txtPesoEjercicioRutina = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDescansoRutina = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMusculoRutina = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cboDiaRutina = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRutinas = new javax.swing.JTable();
        btnAñadirRutina = new javax.swing.JButton();
        btnBorrarRutina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SuperiorLila.setBackground(new java.awt.Color(102, 0, 102));

        txtBuenosDias.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtBuenosDias.setForeground(new java.awt.Color(255, 255, 255));
        txtBuenosDias.setText("Buenos Dias");

        txtFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setText("Hoy es 14 de Junio de 2025");

        javax.swing.GroupLayout SuperiorLilaLayout = new javax.swing.GroupLayout(SuperiorLila);
        SuperiorLila.setLayout(SuperiorLilaLayout);
        SuperiorLilaLayout.setHorizontalGroup(
            SuperiorLilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuperiorLilaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(SuperiorLilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuenosDias))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SuperiorLilaLayout.setVerticalGroup(
            SuperiorLilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuperiorLilaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtBuenosDias, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        PilarVioleta.setBackground(new java.awt.Color(51, 0, 51));
        PilarVioleta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PilarVioleta.setForeground(new java.awt.Color(255, 255, 255));
        PilarVioleta.setToolTipText("");

        jSeparator1.setBackground(new java.awt.Color(204, 0, 204));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        lblFitnessLife.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFitnessLife.setForeground(new java.awt.Color(255, 255, 255));
        lblFitnessLife.setText("FitnessLife");

        javax.swing.GroupLayout PilarVioletaLayout = new javax.swing.GroupLayout(PilarVioleta);
        PilarVioleta.setLayout(PilarVioletaLayout);
        PilarVioletaLayout.setHorizontalGroup(
            PilarVioletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PilarVioletaLayout.createSequentialGroup()
                .addGroup(PilarVioletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PilarVioletaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PilarVioletaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblFitnessLife)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        PilarVioletaLayout.setVerticalGroup(
            PilarVioletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PilarVioletaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblFitnessLife, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtMensaje.setText("Un gusto volver a verte ❤");

        BotonAñadir.setBackground(new java.awt.Color(51, 0, 51));
        BotonAñadir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonAñadir.setForeground(new java.awt.Color(255, 255, 255));
        BotonAñadir.setText("AÑADIR");
        BotonAñadir.setBorder(null);
        BotonAñadir.setBorderPainted(false);
        BotonAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirActionPerformed(evt);
            }
        });

        btnBorrarAlumno.setBackground(new java.awt.Color(51, 0, 51));
        btnBorrarAlumno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBorrarAlumno.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarAlumno.setText("BORRAR");
        btnBorrarAlumno.setBorder(null);
        btnBorrarAlumno.setBorderPainted(false);
        btnBorrarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarAlumnoActionPerformed(evt);
            }
        });

        tblRegistroAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "Title 6", "Title 7", "null"
            }
        ));
        tblRegistroAlumnos.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tblRegistroAlumnos);
        tblRegistroAlumnos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblRegistroAlumnos.getColumnModel().getColumnCount() > 0) {
            tblRegistroAlumnos.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellido:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DNI:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Peso(KG):");

        txtNombreAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAlumnoActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Altura:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Género:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Rutina:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Dias/semana:");

        txtDiasAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiasAlumnoActionPerformed(evt);
            }
        });

        cboGeneroAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cboGeneroAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGeneroAlumnoActionPerformed(evt);
            }
        });

        cboRutina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hipertrofia", "Fuerza ", "Ac. Fis.", "Perdida Peso", "Rehab" }));
        cboRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRutinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAlumnosLayout = new javax.swing.GroupLayout(PanelAlumnos);
        PanelAlumnos.setLayout(PanelAlumnosLayout);
        PanelAlumnosLayout.setHorizontalGroup(
            PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelAlumnosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAlumnosLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAlumnosLayout.createSequentialGroup()
                        .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDniAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPesoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(26, 26, 26)
                .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboGeneroAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlturaAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboRutina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiasAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAñadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );
        PanelAlumnosLayout.setVerticalGroup(
            PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAlumnosLayout.createSequentialGroup()
                .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelAlumnosLayout.createSequentialGroup()
                        .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAlumnosLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlturaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAlumnosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboGeneroAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAlumnosLayout.createSequentialGroup()
                                .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelAlumnosLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel3))
                                    .addGroup(PanelAlumnosLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cboRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))))
                                .addGap(23, 23, 23)
                                .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(txtPesoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelAlumnosLayout.createSequentialGroup()
                                        .addGroup(PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtDiasAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(3, 3, 3))))
                            .addGroup(PanelAlumnosLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtDniAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelAlumnosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alumnos", PanelAlumnos);

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Ejercicios:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Series/Repeticiones:");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("PesoEjercicio:");

        txtEjerciciosRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEjerciciosRutinaActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Descanso:");

        txtDescansoRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescansoRutinaActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Musculo Objetivo:");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Dia:");

        cboDiaRutina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));

        tblRutinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ejercicios", "Series/Repeticiones", "PesoEjercicio", "Descanso", "Musculo Objetivo", "Dia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRutinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRutinasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRutinas);

        btnAñadirRutina.setBackground(new java.awt.Color(51, 0, 51));
        btnAñadirRutina.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadirRutina.setText("AÑADIR");
        btnAñadirRutina.setBorder(null);
        btnAñadirRutina.setBorderPainted(false);
        btnAñadirRutina.setMaximumSize(new java.awt.Dimension(70, 60));
        btnAñadirRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirRutinaActionPerformed(evt);
            }
        });

        btnBorrarRutina.setBackground(new java.awt.Color(51, 0, 51));
        btnBorrarRutina.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarRutina.setText("BORRAR");
        btnBorrarRutina.setBorder(null);
        btnBorrarRutina.setBorderPainted(false);
        btnBorrarRutina.setMaximumSize(new java.awt.Dimension(70, 60));
        btnBorrarRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarRutinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRutinasLayout = new javax.swing.GroupLayout(PanelRutinas);
        PanelRutinas.setLayout(PanelRutinasLayout);
        PanelRutinasLayout.setHorizontalGroup(
            PanelRutinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
            .addGroup(PanelRutinasLayout.createSequentialGroup()
                .addGroup(PanelRutinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRutinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelRutinasLayout.createSequentialGroup()
                        .addComponent(txtEjerciciosRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel12))
                    .addGroup(PanelRutinasLayout.createSequentialGroup()
                        .addComponent(txtPesoEjercicioRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addGroup(PanelRutinasLayout.createSequentialGroup()
                        .addComponent(txtSeriesRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(PanelRutinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescansoRutina)
                    .addComponent(txtMusculoRutina)
                    .addComponent(cboDiaRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(PanelRutinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAñadirRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelRutinasLayout.setVerticalGroup(
            PanelRutinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRutinasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelRutinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEjerciciosRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtDescansoRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(btnAñadirRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelRutinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRutinasLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(PanelRutinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRutinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMusculoRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addGroup(PanelRutinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSeriesRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))
                        .addGap(14, 14, 14)
                        .addGroup(PanelRutinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPesoEjercicioRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(cboDiaRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRutinasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rutinas", PanelRutinas);

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(PilarVioleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SuperiorLila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PilarVioleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SuperiorLila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirActionPerformed
       try{
        Alumnos alumno = new Alumnos();
       alumno.setNombre(txtNombreAlumno.getText());
       alumno.setApellido(txtApellidoAlumno.getText());
       alumno.setDni(Integer.parseInt(txtDniAlumno.getText()));
       alumno.setPeso(Integer.parseInt(txtPesoAlumno.getText()));
       alumno.setAltura(Double.parseDouble(txtAlturaAlumno.getText()));
       alumno.setGenero(cboGeneroAlumno.getSelectedItem().toString());
       alumno.setRutina(cboRutina.getSelectedItem().toString());
       alumno.setDias(Integer.parseInt(txtDiasAlumno.getText()));
       listaAlumnos.add(alumno);
       txtNombreAlumno.setText("");
       txtApellidoAlumno.setText("");
       txtDniAlumno.setText("");
       txtPesoAlumno.setText("");
       txtAlturaAlumno.setText("");
       txtDiasAlumno.setText("");
       refrescarTablaAlumno();
       } catch (Exception e){
       JOptionPane.showMessageDialog(this, "ERROR");
       }
    }//GEN-LAST:event_BotonAñadirActionPerformed

    private void btnBorrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarAlumnoActionPerformed
        int fila = tblRegistroAlumnos.getSelectedRow();
        if (fila!= -1){
            tablaAlumno.removeRow(fila);
            listaAlumnos.remove(fila);
            
        }
    }//GEN-LAST:event_btnBorrarAlumnoActionPerformed

    private void txtNombreAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAlumnoActionPerformed

    private void cboRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRutinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRutinaActionPerformed

    private void cboGeneroAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGeneroAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGeneroAlumnoActionPerformed

    private void txtDiasAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiasAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasAlumnoActionPerformed

    private void txtEjerciciosRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEjerciciosRutinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEjerciciosRutinaActionPerformed

    private void txtDescansoRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescansoRutinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescansoRutinaActionPerformed

    private void btnAñadirRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirRutinaActionPerformed
        try{
            Rutinas rutina = new Rutinas();
            rutina.setEjercicio(txtEjerciciosRutina.getText());
            rutina.setSeriesRepeticiones(Integer.parseInt(txtSeriesRutina.getText()));
            rutina.setPesoEjercicio(Integer.parseInt(txtPesoEjercicioRutina.getText()));
            rutina.setDescanso(Integer.parseInt(txtDescansoRutina.getText()));
            rutina.setMusculoObjetivo(txtMusculoRutina.getText());
            rutina.setDia(cboDiaRutina.getSelectedItem().toString());
            listaRutinas.add(rutina);
            txtEjerciciosRutina.setText("");
            txtSeriesRutina.setText("");
            txtPesoEjercicioRutina.setText("");
            txtDescansoRutina.setText("");
            txtMusculoRutina.setText("");
            refrescarTablaRutina();
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");    
            }
    }//GEN-LAST:event_btnAñadirRutinaActionPerformed

    private void tblRutinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRutinasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRutinasMouseClicked

    private void btnBorrarRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarRutinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarRutinaActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         FlatMTMaterialLighterIJTheme.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FitnessApp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAñadir;
    private javax.swing.JPanel PanelAlumnos;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelRutinas;
    private javax.swing.JPanel PilarVioleta;
    private javax.swing.JPanel SuperiorLila;
    private javax.swing.JButton btnAñadirRutina;
    private javax.swing.JButton btnBorrarAlumno;
    private javax.swing.JButton btnBorrarRutina;
    private javax.swing.JComboBox<String> cboDiaRutina;
    private javax.swing.JComboBox<String> cboGeneroAlumno;
    private javax.swing.JComboBox<String> cboRutina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblFitnessLife;
    private javax.swing.JTable tblRegistroAlumnos;
    private javax.swing.JTable tblRutinas;
    private javax.swing.JTextField txtAlturaAlumno;
    private javax.swing.JTextField txtApellidoAlumno;
    private javax.swing.JLabel txtBuenosDias;
    private javax.swing.JTextField txtDescansoRutina;
    private javax.swing.JTextField txtDiasAlumno;
    private javax.swing.JTextField txtDniAlumno;
    private javax.swing.JTextField txtEjerciciosRutina;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtMensaje;
    private javax.swing.JTextField txtMusculoRutina;
    private javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JTextField txtPesoAlumno;
    private javax.swing.JTextField txtPesoEjercicioRutina;
    private javax.swing.JTextField txtSeriesRutina;
    // End of variables declaration//GEN-END:variables
}