/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FitnessLife;


import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Alumnos;


/**
 *
 * @author ALE
 */
public class FitnessApp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FitnessApp.class.getName());

    
    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<Alumnos> listaAlumnos = new ArrayList<Alumnos>();
    
  
    
    public void refrescarTabla(){
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        
        for (Alumnos alumno : listaAlumnos){
        Object a[] = new Object[8];
        a[0] = alumno.getNombre();
        a[1] = alumno.getApellido();
        a[2] = alumno.getDni();
        a[3] = alumno.getPeso();
        a[4] = alumno.getAltura();
        a[5] = alumno.getGenero();
        a[6] = alumno.getRutina();
        a[7] = alumno.getDias();
        modelo.addRow(a);
        }
        tblRegistroAlumnos.setModel(modelo);
    }
    public FitnessApp() {
        initComponents();
        InitStyles();
        this.setTitle("Alumnos");
        this.setSize(900, 700);
        this.setLocationRelativeTo(null);
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("DNI");
        modelo.addColumn("Peso(KG)");
        modelo.addColumn("Altura");
        modelo.addColumn("Género");
        modelo.addColumn("Rutina");
        modelo.addColumn("Dias/semana");
        refrescarTabla();
    }
    private void InitStyles(){
        
        txtMensaje.putClientProperty( "FlatLaf.style", "font: 14 $light.font" );
        txtMensaje.setForeground(Color.black);
    }
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        SuperiorLila = new javax.swing.JPanel();
        txtBuenosDias = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        PilarVioleta = new javax.swing.JPanel();
        BotonAlumno = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblFitnessLife = new javax.swing.JLabel();
        BotonRutinas = new javax.swing.JButton();
        PanelMedio = new javax.swing.JPanel();
        BotonGuardar = new javax.swing.JButton();
        BotonAñadir = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegistroAlumnos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        txtApellidoAlumno = new javax.swing.JTextField();
        txtDniAlumno = new javax.swing.JTextField();
        txtPesoAlumno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDiasAlumno = new javax.swing.JTextField();
        txtAlturaAlumno = new javax.swing.JTextField();
        cboGeneroAlumno = new javax.swing.JComboBox<>();
        cboRutina = new javax.swing.JComboBox<>();
        txtMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SuperiorLila.setBackground(new java.awt.Color(153, 0, 153));

        txtBuenosDias.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtBuenosDias.setForeground(new java.awt.Color(255, 255, 255));
        txtBuenosDias.setText("Buenos Dias Santiago");

        txtFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setText("Hoy es 14 de Junio de 2025");

        javax.swing.GroupLayout SuperiorLilaLayout = new javax.swing.GroupLayout(SuperiorLila);
        SuperiorLila.setLayout(SuperiorLilaLayout);
        SuperiorLilaLayout.setHorizontalGroup(
            SuperiorLilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuperiorLilaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(465, Short.MAX_VALUE))
            .addGroup(SuperiorLilaLayout.createSequentialGroup()
                .addComponent(txtBuenosDias)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SuperiorLilaLayout.setVerticalGroup(
            SuperiorLilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuperiorLilaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtBuenosDias, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        PilarVioleta.setBackground(new java.awt.Color(51, 0, 51));

        BotonAlumno.setBackground(new java.awt.Color(51, 0, 51));
        BotonAlumno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonAlumno.setForeground(new java.awt.Color(255, 255, 255));
        BotonAlumno.setText("Alumnos");
        BotonAlumno.setBorder(null);
        BotonAlumno.setBorderPainted(false);
        BotonAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAlumno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlumnoActionPerformed(evt);
            }
        });

        lblFitnessLife.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFitnessLife.setForeground(new java.awt.Color(255, 255, 255));
        lblFitnessLife.setText("FitnessLife");

        BotonRutinas.setBackground(new java.awt.Color(51, 0, 51));
        BotonRutinas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonRutinas.setForeground(new java.awt.Color(255, 255, 255));
        BotonRutinas.setText("Rutinas");
        BotonRutinas.setBorder(null);
        BotonRutinas.setBorderPainted(false);
        BotonRutinas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRutinas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonRutinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRutinasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PilarVioletaLayout = new javax.swing.GroupLayout(PilarVioleta);
        PilarVioleta.setLayout(PilarVioletaLayout);
        PilarVioletaLayout.setHorizontalGroup(
            PilarVioletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonRutinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PilarVioletaLayout.createSequentialGroup()
                .addGroup(PilarVioletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PilarVioletaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PilarVioletaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblFitnessLife)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        PilarVioletaLayout.setVerticalGroup(
            PilarVioletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PilarVioletaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblFitnessLife, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(BotonAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonRutinas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        BotonGuardar.setBackground(new java.awt.Color(51, 0, 51));
        BotonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BotonGuardar.setText("GUARDAR");
        BotonGuardar.setBorder(null);
        BotonGuardar.setBorderPainted(false);
        BotonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonAñadir.setBackground(new java.awt.Color(51, 0, 51));
        BotonAñadir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonAñadir.setForeground(new java.awt.Color(255, 255, 255));
        BotonAñadir.setText("AÑADIR");
        BotonAñadir.setBorder(null);
        BotonAñadir.setBorderPainted(false);
        BotonAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirActionPerformed(evt);
            }
        });

        BotonBorrar.setBackground(new java.awt.Color(51, 0, 51));
        BotonBorrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonBorrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonBorrar.setText("BORRAR");
        BotonBorrar.setBorder(null);
        BotonBorrar.setBorderPainted(false);
        BotonBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });

        tblRegistroAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "Title 6", "Title 7", "null"
            }
        ));
        tblRegistroAlumnos.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tblRegistroAlumnos);
        tblRegistroAlumnos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblRegistroAlumnos.getColumnModel().getColumnCount() > 0) {
            tblRegistroAlumnos.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("DNI:");

        jLabel4.setText("Peso(KG):");

        txtNombreAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAlumnoActionPerformed(evt);
            }
        });

        jLabel5.setText("Altura:");

        jLabel6.setText("Género:");

        jLabel7.setText("Rutina:");

        jLabel8.setText("Dias/semana:");

        txtDiasAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiasAlumnoActionPerformed(evt);
            }
        });

        cboGeneroAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cboGeneroAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGeneroAlumnoActionPerformed(evt);
            }
        });

        cboRutina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hipertrofia", "Fuerza ", "Ac. Fis.", "Perdida Peso", "Rehab" }));
        cboRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRutinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMedioLayout = new javax.swing.GroupLayout(PanelMedio);
        PanelMedio.setLayout(PanelMedioLayout);
        PanelMedioLayout.setHorizontalGroup(
            PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMedioLayout.createSequentialGroup()
                .addGroup(PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMedioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(PanelMedioLayout.createSequentialGroup()
                        .addGroup(PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMedioLayout.createSequentialGroup()
                                .addGroup(PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelMedioLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelMedioLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMedioLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(16, 16, 16)))
                        .addGroup(PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(txtApellidoAlumno)
                            .addComponent(txtDniAlumno)
                            .addComponent(txtPesoAlumno))
                        .addGap(48, 48, 48)
                        .addGroup(PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboRutina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDiasAlumno)
                            .addComponent(cboGeneroAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAlturaAlumno))
                        .addGap(74, 74, 74)
                        .addGroup(PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelMedioLayout.setVerticalGroup(
            PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMedioLayout.createSequentialGroup()
                .addGroup(PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMedioLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtAlturaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cboGeneroAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelMedioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BotonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMedioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDniAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cboRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPesoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtDiasAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelMedioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtMensaje.setText("Un gusto volver a verte ❤");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(PilarVioleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SuperiorLila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PilarVioleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SuperiorLila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAlumnoActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void BotonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirActionPerformed
       try{
        Alumnos alumno = new Alumnos();
       alumno.setNombre(txtNombreAlumno.getText());
       alumno.setApellido(txtApellidoAlumno.getText());
       alumno.setDni(Integer.parseInt(txtDniAlumno.getText()));
       alumno.setPeso(Integer.parseInt(txtPesoAlumno.getText()));
       alumno.setAltura(Double.parseDouble(txtAlturaAlumno.getText()));
       alumno.setGenero(cboGeneroAlumno.getSelectedItem().toString());
       alumno.setRutina(cboRutina.getSelectedItem().toString());
       alumno.setDias(Integer.parseInt(txtDiasAlumno.getText()));
       listaAlumnos.add(alumno);
       refrescarTabla();
       } catch (Exception e){
       JOptionPane.showMessageDialog(this, "ERROR");
       }
    }//GEN-LAST:event_BotonAñadirActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void BotonRutinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRutinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRutinasActionPerformed

    private void txtNombreAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAlumnoActionPerformed

    private void cboRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRutinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRutinaActionPerformed

    private void cboGeneroAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGeneroAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGeneroAlumnoActionPerformed

    private void txtDiasAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiasAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         FlatMTMaterialLighterIJTheme.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FitnessApp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAlumno;
    private javax.swing.JButton BotonAñadir;
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonRutinas;
    private javax.swing.JPanel PanelMedio;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PilarVioleta;
    private javax.swing.JPanel SuperiorLila;
    private javax.swing.JComboBox<String> cboGeneroAlumno;
    private javax.swing.JComboBox<String> cboRutina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFitnessLife;
    private javax.swing.JTable tblRegistroAlumnos;
    private javax.swing.JTextField txtAlturaAlumno;
    private javax.swing.JTextField txtApellidoAlumno;
    private javax.swing.JLabel txtBuenosDias;
    private javax.swing.JTextField txtDiasAlumno;
    private javax.swing.JTextField txtDniAlumno;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtMensaje;
    private javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JTextField txtPesoAlumno;
    // End of variables declaration//GEN-END:variables
}
